name: CI/CD Automation

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
jobs:
  # Job to build and test on dev branch
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for frontend and backend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run unit tests for frontend
      run: |
        cd frontend
        npm test

    - name: Run unit tests for backend
      run: |
        cd backend
        npm test
        
    - name: Merge dev to main (if tests pass)
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch origin dev
        git checkout main
        git merge origin/dev --allow-unrelated-histories
        git push origin main

  # Job to build, test, and deploy for main branch
  build_and_deploy_main:
    needs: build_and_test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for frontend and backend
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run unit tests for frontend
      run: |
        cd frontend
        npm test

    - name: Run unit tests for backend
      run: |
        cd backend
        npm test

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  
    - name: Run E2E tests
      run: |
        cd e2e-tests
        docker-compose up
        npm test
        docker-compse down

    - name: Build Docker images using docker-compose
      run: |
        docker-compose -f docker-compose.yml build

    - name: Push Docker images to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker-compose -f docker-compose.yml push
